# Generated by Django 4.1.2 on 2022-11-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "character_race",
                    models.CharField(
                        choices=[
                            ("Dragonborn", "Dragonborn"),
                            ("Dwarf", "Dwarf"),
                            ("Elf", "Elf"),
                            ("Gnome", "Gnome"),
                            ("Half-Elf", "Half Elf"),
                            ("Halfling", "Halfling"),
                            ("Half-Orc", "Half Orc"),
                            ("Human", "Human"),
                            ("Tiefling", "Tiefling"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "character_class",
                    models.CharField(
                        choices=[
                            ("Barbarian", "Barbarian"),
                            ("Bard", "Bard"),
                            ("Cleric", "Cleric"),
                            ("Druid", "Driud"),
                            ("Fighter", "Fighter"),
                            ("Monk", "Monk"),
                            ("Paladin", "Paladin"),
                            ("Ranger", "Ranger"),
                            ("Rogue", "Rogue"),
                            ("Sorcerer", "Sorcerer"),
                            ("Warlock", "Warlock"),
                            ("Wizard", "Wizard"),
                        ],
                        max_length=25,
                    ),
                ),
                ("biography", models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
